version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grupo02
      POSTGRES_DB:  db.db
    volumes:
      - ./scripts/000_setup.sql:/docker-entrypoint-initdb.d/000_setup.sql:ro

