version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"  # Expondo a porta 5432 para conexões externas
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust  # Configurando o método de autenticação do host para trust

